# Generated by Django 4.2.8 on 2024-01-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_cartproduct_orderproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipe',
            field=models.FileField(null=True, upload_to='recipe_photos/', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('accepted', 'Принят'), ('canceled', 'Отменен')], default='processing', max_length=20),
        ),
    ]
