# Generated by Django 4.2.8 on 2024-01-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_comments_alter_order_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('accepted', 'Принят'), ('canceled', 'Отменен'), ('done', 'Доставлен')], default='processing', max_length=20),
        ),
    ]
