# Generated by Django 4.2.8 on 2024-01-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('accepted', 'Принят'), ('canceled', 'Отменен'), ('done', 'Доставлен')], default='processing', max_length=20, verbose_name='Статус'),
        ),
    ]
